###############################################################################
# Compiler and base flags
###############################################################################
# CXX is intentionally NOT hard-set: it defaults to make's built-in `g++` (an
# Apple clang shim on macOS). Leaving it as the built-in default lets
# `make TARGET=windows` auto-select the MinGW cross compiler (see target block)
# and lets cross builds override it on the command line.
# Added -Wall -Wextra for safety, and -MMD -MP for automatic header dependency tracking
CXXFLAGS := -std=c++17 -Wall -Wextra -MMD -MP
CPPFLAGS :=
LDFLAGS  :=

###############################################################################
# Host detection (the machine running make) -> RM / MKDIR / default TARGET
###############################################################################
ifeq ($(OS),Windows_NT)
    HOST_OS := windows
    RM      := del /Q
    MKDIR   := mkdir
else
    UNAME_S := $(shell uname -s)
    ifeq ($(UNAME_S),Linux)
        HOST_OS := linux
    else ifeq ($(UNAME_S),Darwin)
        HOST_OS := macos
    endif
    RM      := rm -f
    MKDIR   := mkdir -p
endif

###############################################################################
# Target OS selection (enables cross-compiling from any host).
#   Native build (default):  make ARCH=native
#   Windows cross-build:      make TARGET=windows ARCH=x86-64-avx2  \
#                                  CXX=x86_64-w64-mingw32-g++
#   Linux cross-build:        make TARGET=linux   ARCH=x86-64-avx512 \
#                                  CXX=x86_64-unknown-linux-gnu-g++
# TARGET defaults to the host OS so a plain `make` is unchanged.
###############################################################################
TARGET ?= $(HOST_OS)

ifeq ($(TARGET),windows)
    OS_NAME    := Windows
    EXE_SUFFIX := .exe
    STACK_FLAG := -Wl,--stack,8388608
    # Statically link the GCC/libstdc++/winpthread runtimes into the .exe so it
    # has ZERO external GCC DLL dependencies. Without this, the exe loads whatever
    # libstdc++-6.dll / libgcc_s_seh-1.dll / libwinpthread-1.dll it finds on PATH,
    # and a mismatched copy triggers "entry point _ZSt11_once_call / _emutls_v.
    # not found in the DLL" at startup (std::call_once + pthread TLS live there).
    LDFLAGS += -static -static-libgcc -static-libstdc++
    # Default to the MinGW-w64 cross compiler unless the user overrode CXX.
    ifeq ($(origin CXX),default)
        CXX := x86_64-w64-mingw32-g++
    endif
else ifeq ($(TARGET),linux)
    OS_NAME    := Linux
    EXE_SUFFIX :=
    STACK_FLAG :=
    # Partial-static: bundle libstdc++/libgcc so the binary runs on distros with
    # older GLIBCXX/libgcc than the build host (glibc itself stays dynamic).
    LDFLAGS += -static-libgcc -static-libstdc++
else
    OS_NAME    := macOS
    EXE_SUFFIX :=
    STACK_FLAG := # No stack flag for macOS
endif

###############################################################################
# Source and object files (sources live in src/; objects sit beside them)
###############################################################################
SOURCES := $(wildcard src/*.cpp)
OBJECTS := $(SOURCES:.cpp=.o)
# Dependency files generated by -MMD
DEPS    := $(OBJECTS:.o=.d)

###############################################################################
# Embedded default NNUE network
#   The .nnue file is compiled directly into the binary (via .incbin in
#   src/nnue_embedded_data.S) so the engine works standalone without a .nnue
#   file sitting next to the executable. Override with:
#     make NNUE_FILE=/path/to/other.nnue
###############################################################################
NNUE_FILE ?= $(abspath nn/thrawn-nn-2.nnue)
NNUE_NAME := $(basename $(notdir $(NNUE_FILE)))
EMBED_OBJ := src/nnue_embedded_data.o

# Surfaced in UCI info strings (e.g. "Loaded embedded default NNUE (thrawn-nn-2)").
CPPFLAGS += -DNNUE_EMBED_NAME='"$(NNUE_NAME)"'

# Skip this check for clean/distclean, which don't need the net present.
ifeq ($(filter clean distclean,$(MAKECMDGOALS)),)
ifeq ($(wildcard $(NNUE_FILE)),)
$(error NNUE network not found at '$(NNUE_FILE)'. Place the .nnue file there, \
or build with `make NNUE_FILE=/path/to/net.nnue`)
endif
endif

OBJECTS += $(EMBED_OBJ)

###############################################################################
# Build type and flags
###############################################################################
BUILD ?= release
ARCH  ?= native

OPT_FLAGS  := -O3 -flto=auto
ARCH_FLAGS :=
MACOS_MIN_VERSION := 10.15

# Host machine arch, consumed only by the ARCH=native path (native builds only;
# cross builds must pass an explicit ARCH such as x86-64-avx2 / x86-64-avx512).
ifeq ($(HOST_OS),windows)
    ARCH_DETECTED := $(PROCESSOR_ARCHITECTURE)
else
    ARCH_DETECTED := $(shell uname -m)
endif

# Target-OS-specific compile/link additions.
ifeq ($(TARGET),linux)
    CXXFLAGS += -pthread
    LDFLAGS  += -pthread
else ifeq ($(TARGET),macos)
    ifeq ($(ARCH_DETECTED),arm64)
        MACOS_MIN_VERSION := 11.0
    endif
    ARCH_FLAGS += -mmacosx-version-min=$(MACOS_MIN_VERSION)
else ifeq ($(TARGET),windows)
    CPPFLAGS += -DWIN32
endif

# -----------------------------------------------------------------------------
# Architecture specific flags
# -----------------------------------------------------------------------------
ifeq ($(ARCH),native)
    ifeq ($(ARCH_DETECTED),x86_64)
        CPPFLAGS += -DUSE_AVX2
        ARCH_FLAGS += -march=native -mfma -mbmi -mbmi2 -mpopcnt
        DIST_TAG := x64-avx2
    else ifeq ($(ARCH_DETECTED),AMD64)
        CPPFLAGS += -DUSE_AVX2
        ARCH_FLAGS += -march=native -mfma -mbmi -mbmi2 -mpopcnt
        DIST_TAG := x64-avx2
    else ifeq ($(ARCH_DETECTED),arm64)
        CPPFLAGS += -DUSE_NEON
        ARCH_FLAGS += -march=native
        DIST_TAG := arm-neon
    else ifeq ($(ARCH_DETECTED),aarch64)
        CPPFLAGS += -DUSE_NEON
        ARCH_FLAGS += -march=native
        DIST_TAG := arm-neon
    else ifeq ($(ARCH_DETECTED),ARM64)
        CPPFLAGS += -DUSE_NEON
        ARCH_FLAGS += -march=native
        DIST_TAG := arm-neon
    endif
else ifeq ($(ARCH),x86-64-avx512)
    CPPFLAGS += -DUSE_AVX512
    ARCH_FLAGS += -mavx512f -mavx512bw -mavx512dq -mavx512vnni -mavx2 -mfma -mbmi -mbmi2 -mpopcnt
    DIST_TAG := x64-avx512
else ifeq ($(ARCH),x86-64-avx2)
    CPPFLAGS += -DUSE_AVX2
    ARCH_FLAGS += -mavx2 -mfma -mbmi -mbmi2 -mpopcnt
    DIST_TAG := x64-avx2
else ifeq ($(ARCH),arm64-neon)
    CPPFLAGS += -DUSE_NEON
    DIST_TAG := arm-neon
else ifeq ($(ARCH),arm64-neon-dotprod)
    CPPFLAGS += -DUSE_NEON
    ifeq ($(OS_NAME),macOS)
        ARCH_FLAGS += -march=native
    else
        ARCH_FLAGS += -march=armv8.2-a+dotprod
    endif
    DIST_TAG := arm-neon
else
    $(error Unsupported ARCH '$(ARCH)'. Use native, x86-64-avx512, x86-64-avx2, arm64-neon, or arm64-neon-dotprod)
endif

# -----------------------------------------------------------------------------
# PEXT bitboards (opt-in: `make PEXT=1`)
# -----------------------------------------------------------------------------
# Replaces magic-multiply slider indexing with the BMI2 PEXT instruction and
# packed (fancy) attack tables. Recommended ONLY on Intel Haswell+ and AMD Zen3+
# where PEXT is fast; it is microcoded/slow on pre-Zen3 AMD. On non-BMI2 targets
# (e.g. arm64) a portable software-PEXT fallback is used (correct, but slow).
ifeq ($(PEXT),1)
    CPPFLAGS += -DUSE_PEXT
    ifneq ($(filter x86_64 AMD64,$(ARCH_DETECTED)),)
        ARCH_FLAGS += -mbmi2
    endif
endif

# -----------------------------------------------------------------------------
# Build Types
# -----------------------------------------------------------------------------
ifeq ($(BUILD),debug)
    CPPFLAGS += -DDEBUG_BUILD
    CXXFLAGS += -g $(ARCH_FLAGS)
else ifeq ($(BUILD),release)
    CPPFLAGS += -DRELEASE_BUILD -DNDEBUG
    CXXFLAGS += $(OPT_FLAGS) $(ARCH_FLAGS)
    # LTO requires the optimization flag at link time as well
    LDFLAGS  += $(OPT_FLAGS) 
endif

###############################################################################
# Distribution output
#   All binaries land in a build/ directory at the repo root, named:
#     build/thrawn-v<VERSION>-<os>-<simd>[.exe]
#   e.g. build/thrawn-v3.1-macos-arm-neon, build/thrawn-v3.1-windows-x64-avx2.exe
###############################################################################
VERSION     ?= 3.1
BUILD_DIR   ?= $(abspath $(CURDIR)/build)
OUTPUT_NAME ?= thrawn-v$(VERSION)-$(TARGET)-$(DIST_TAG)$(EXE_SUFFIX)
OUTPUT      := $(BUILD_DIR)/$(OUTPUT_NAME)

###############################################################################
# Targets
###############################################################################
.PHONY: all clean distclean release

# Removed the forced "clean" on every make call so incremental builds work
all: $(OUTPUT)

$(OUTPUT): $(OBJECTS) | $(BUILD_DIR)
	$(CXX) $(CXXFLAGS) $(LDFLAGS) $(STACK_FLAG) -o $@ $^

$(BUILD_DIR):
	$(MKDIR) "$(BUILD_DIR)"

%.o: %.cpp
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c -o $@ $<

# Assembles the embedded-NNUE .S file. No C++ optimization/warning flags apply
# to a pure data/.incbin translation unit; ARCH_FLAGS is included only so the
# object's target-platform version metadata (e.g. -mmacosx-version-min) matches
# the rest of the build and avoids a linker version-mismatch warning.
$(EMBED_OBJ): src/nnue_embedded_data.S $(NNUE_FILE)
	$(CXX) $(CPPFLAGS) -DNNUE_EMBED_PATH='"$(NNUE_FILE)"' $(ARCH_FLAGS) -c -o $@ $<

# clean removes only intermediates (objects/deps), never the build/ artifacts, so
# `release` can accumulate all five binaries across successive arch builds.
clean:
	$(RM) $(OBJECTS) $(DEPS)

distclean: clean
	$(RM) -r "$(BUILD_DIR)"

# Build all five distributable binaries into $(BUILD_DIR). Intended to run on an
# Apple Silicon macOS host with mingw-w64 and the x86_64-unknown-linux-gnu cross
# toolchain installed (via Homebrew). Objects are cleaned between archs because
# each uses different -march / -D flags. Run with no extra args.
release:
	$(MAKE) clean
	$(MAKE) TARGET=macos   ARCH=native
	$(MAKE) clean
	$(MAKE) TARGET=windows ARCH=x86-64-avx2   CXX=x86_64-w64-mingw32-g++
	$(MAKE) clean
	$(MAKE) TARGET=windows ARCH=x86-64-avx512 CXX=x86_64-w64-mingw32-g++
	$(MAKE) clean
	$(MAKE) TARGET=linux   ARCH=x86-64-avx2   CXX=x86_64-unknown-linux-gnu-g++
	$(MAKE) clean
	$(MAKE) TARGET=linux   ARCH=x86-64-avx512 CXX=x86_64-unknown-linux-gnu-g++
	$(MAKE) clean
	@echo "==> Distributable binaries in $(BUILD_DIR):"
	@ls -la "$(BUILD_DIR)"

# Include automatically generated dependency files
-include $(DEPS)